apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTVHbjNwd0djeHRoUXBYZDh0RjhhYlhYUnYwSVBGOHkzdHpIbXU3UnUzZ25pCk5iQUt4OE42UXJvaU9xbWVKMkt4am1CbEM0cUJsRllMRm1RWisvVmNqSFZ3S2dQc0dzUW5Cd1l1bG5pd2xJZjkKTDJ6Tkc4c2w1Z1J6TnVpYUpUYVNWUVBNY3hXSktGY1NCdVpYQjVBTVJUemNObkc1WVlZQTR6K1JLOHk5bDIrRApJZEQ5UURocEVNYVJOb0FSNXAvLzBBTG5FVGhvaEl1T3lBdFVxc3FKeXlmUTZjMjNqYlRvVjNuR1dZNWRvellpCkZTUTdUTjNvL0Z5S056eDVzNFBTY01VRkxDUGNwcnY4WkxJckpWdlp0cnlvM3ZqL2lEeFlja00wOTh4MXBIOVIKc2tQM3EvZ3d6M0FmS1h3RWJBMUUzZnNrNFhTUElKd0FpdWpXN3NZdXN3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSXRmckw0ZzZEODJPM3FlakUzeDVGZFZOL2dQcjNRYUlWeDRzZ2U0M1VHS2hUbjV3cXBIClRPc1BDOGE1cHZUREJTcG5na1VyMzhMd2VrSlZIblgrSFdZSWh0Z2g2MWxCTTVaclhhMFVjTlBEeE1pM0FSLzcKNmszTm1BQk9obFlEYUhTYW5QN3VGYWlYSFdxa1kzUWREZnl0VlA1S3c0ZXJjRGIxZmtFQnZYRVhBdXNrSFlZWApjenhQRCt1QjQxWGZ5bTRVbHorSVRwcWczQ1luL2FMV21NRFhPVkJRTzVOWmp6ZVB1SWlzRG9XUlowL0VmMkdKClAxd3F4a0hjY0FRcThWUHFORHJNQ1A1NzZrWDIzN0ZXQXNvTHVjQzMyODRhUUcxVTd3SjEwemU2dG1ocE5IQ2IKbWJLL2pXM1E2VnlDY05VeTVQdjZjU1J2blR4OUFlZ053YXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth