#Deploy a DaemonSet for FluentD Logging.
#Name: elasticsearch
#Namespace: kube-system
#Image: k8s.gcr.io/fluentd-elasticsearch:1.20
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    name: elasticsearch
spec:
  template:
    metadata:
      name: elasticsearch
      namespace: kube-system
      labels:
        name: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: k8s.gcr.io/fluentd-elasticsearch:1.20
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
  selector:
    matchLabels:
      name: elasticsearch
