#Set Node Affinity to the deployment to place the PODs on node01 only
#Name: blue
#Replicas: 6
#Image: nginx
#NodeAffinity: requiredDuringSchedulingIgnoredDuringExecution
#Key: color
#values: blue

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    color: blue


spec:
  replicas: 6
  template:
    metadata:
      name: blue
      labels:
        color: blue
    spec:
      containers:
        - name: blue
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: color
                  operator: In
                  values:
                  -  blue

  selector:
    matchLabels:
      color: blue

