apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    scheduler: custom
spec:
  template:
    metadata:
      name: nginx
      labels:
        scheduler: custom
    spec:
      containers:
        - name: nginx
          image: nginx
  schedulerName: my-scheduler

