apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTRObDFkQjBHZHVIZ25HNXZQc3hISnozRExHblRZNzdpSy90MmQyWlRNUVBtCjlVYXNicFZoMXhnMmV5UDFXd2c2M0FrbVRYMjNRWjFsZTlvWVlRT2c5Y3doTEtDOEVZQ3ZzRStJd1djNWRNeEkKYTVFbUNydDJ4bmVkTEVDRXZhaGNrNGI0OU1ic1p4NzdJQ0RCdU9OY29UUU5CbWtwaHAyU0hLM2dZVXRvUkl5Rgp2RFJNQ2FwbmZzd08xdkFPL1FGckVqazZ1Rlhqc1FnblhZWDFPV3pGUGFmNG1Ram5PZFN1empwQVN5eUtFRDF6CnFhQlJWR1Z5LzVRWVhkQkYwSUFTRDdKcEYzcytwMGQxMFpvQ2MvZFB2UFdja1UxOG02cCtlV1M0NE1SSFVDNk8KRnNCWVJjK2JYbzc5ZFFTL2VHdnFFTW00ODNhWUZKOXpLSE1TTW9Oay93SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRVgzcU16WXEraXZYU05RbFRoSlQwZDBJS0NhUFJoTnJzdUtCMTF2aWc3c3luZXBWUDdlCkFVWXMvM3hIM3VwM0xUWi9scSt3LzBubDRZSTloYTJqYlZZa2Y1R3VzaWJZamRCcFV0VXJoNVRyYmF4WkcwRG0KOGlVZ2dnTVZCYlZ5MnMxcFEzZWhWM25rSlMvTzBYZmRkajR5Y2twcHBFZTRzV3ZoWC9WQzR1eE9GdjI3STdrUQoxTnQ3MjRZVnR1TndUbVRUSElLYWVONkZsVXdoMXd2UWpKZXN6dXFDZS8wQ3RxYTNUNDhzWUE3Skc0U3BlY2trClRQMDFoS0tvVHE3WVk3ckJlalkzaHdYZXJ2WnJOWkhxUWVCYmpHSnJlN3JMdWJocGtwYllDV0d4L1ozaFFuOHMKNFZmbGp5TVBFcUpkK1VZTzc4WG1kR1pRWnJnUjY5T3NSTTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth