apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
  labels:
    run: web
spec:
  replicas: 2
  template:
    metadata:
       name: web
       namespace: default
       labels:
         run: web
    spec:
      containers:
      - name: nginx
        image: myprivateregistry.com:5000/nginx:alpine
      imagePullSecrets:
      - name: private-reg-cred
  selector:
    matchLabels:
       run: web
##

Name: private-reg-cred
Username: dock_user
Password: dock_password
Server: myprivateregistry.com:5000
Email: dock_user@myprivateregistry.com
master $ kubectl create secret docker-registry private-reg-cred \
> --docker-username=dock-user \
> --docker-password=dock_password \
> --docker-server=myprivateregistry.com:5000 \
> --docker-email=dock_user@myprivateregistry.com
##
