apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-01-02T15:05:55Z"
  name: red
  namespace: default
  resourceVersion: "494"
  selfLink: /api/v1/namespaces/default/pods/red
  uid: 268277bd-2304-407c-af2c-6ea462f21ba1
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: red-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-wxg5p
      readOnly: true
  initContainers:
  - name: init-myservice
    image: busybox
    command:
    - sh
    - -c
    - "sleep 20"