apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2019-12-30T01:19:47Z"
  labels:
    name: webapp-pod
  name: webapp-pod
  namespace: default
  resourceVersion: "769"
  selfLink: /api/v1/namespaces/default/pods/webapp-pod
  uid: 991b4836-90e3-40d0-83f3-907064ace598
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
         name: db-secret