

#Create a new service to access the web application using the service-definition-1.yaml file
#Name: webapp-service; Type: NodePort; targetPort: 8080; port: 8080; nodePort: 30080; selector: simple-webapp

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    name: simple-webapp
spec:
  type: NodePort
  ports:
  -  targetPort: 8080
     port: 8080
     nodePort: 30080
  selector:
    matchLabels:
      name: simple-webapp

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
   selector:
      matchLabels:
         name: simple-webapp
