
#kubectl get pvc
#when persistent volume is protected. You should be able to cross verify this otherwise,
#you will not  be able delete it .
#
#Command:
#
#kubectl describe pvc PVC_NAME | grep Finalizers
#
#Output:
#
#Finalizers:    [kubernetes.io/pvc-protection]
#
#You can fix this by setting finalizers to null using kubectl patch:
#
#kubectl patch pvc PVC_NAME -p '{"metadata":{"finalizers": []}}' --type=merge
#
#


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
