#Name: elasticsearch
#Namespace: kube-system
#Image: k8s.gcr.io/fluentd-elasticsearch:1.20


apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: fluentd
spec:
  template:
    metadata:
      name: elasticsearch
      labels:
        app: fluentd
    spec:
      containers:
        - name: elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      app: fluentd