#!/usr/bin/env bash
echo -e "\t\t**Add a user to a group**\n"
u=$2
g=$3
cupass=$4
if [[ -z "$2" &&  -z "$3" &&  -z "$4" ]]
then
echo $fled_str;
exit 1;
fi
#read -p 'enter the username : ' u
#read -p 'enter the groupname : ' g
/usr/bin/expect -f - <<EOF
set timeout -1
spawn /opt/infocentricity/xeno/xd/bin/xu create -g $g -u $u
match_max 100000

stmt1="Minimum password length: 8\r
Minimum required character classes: 3\r
\r"

stmt2="Minimum password length: 8\r
Minimum required character classes: 1\r
\r



if stemt1 \ stmt2
then
expect -exact $stmt1
Please enter a password for user $u: "
send -- "$cupass\r"
expect -exact "\r
\r
Please re-enter the password: "
send -- "$cupass\r"
expect eof
EOF

#command=" /opt/infocentricity/xeno/xd/bin/xu create -g $g -u $u"
#eval $command
if [ $? == 0 ]
then
echo "User-$u has been added in Group-$g. Your password is $cupass"
fi
;;
